on:
  push:
    branches:
      - master
      - dev
jobs:
  test-build:
    name: NCR_BUILD
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Build
        uses: EasyDesk/action-dotnet-build@v1.0.0
      - name: Upload NCR Client for Windows
        uses: actions/upload-artifact@v4.3.3
        with:
          name: NCRClientWindows
          path: ./UniversalClient/bin/Release/net8.0/
      - name: Upload NCR Installer for Windows
        uses: actions/upload-artifact@v4.3.3
        with:
          name: NCRInstallerWindows
          path: ./UniversalInstaller/bin/Release/net8.0/